<a href="https://colab.research.google.com/github/samuelj1323/By_The_Cover/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
If you have any questions: go to the course github


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


## Intro to Tensors

### Creating a tensor



In [ ]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

Torch tensor: https://pytorch.org/docs/stable/tensors.html
.

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
#Typically has more than one number

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[7,8],
[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random Tensors

Why random tensors?
Random tensors are important because the way taht many NN learn is that htey start with tensors ful of rnadom numbers and hten adjust those random numbers to better represent the data.

`Start with Random number -> look at data => update random numbers => look at data => update the random numbers `

In [ ]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3740, 0.0955, 0.0837, 0.2271],
        [0.5073, 0.3099, 0.2271, 0.8040],
        [0.4442, 0.3585, 0.9479, 0.8080]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(2,3,2)

tensor([[[0.1537, 0.9197],
         [0.4820, 0.5876],
         [0.4430, 0.7320]],

        [[0.7473, 0.4535],
         [0.1143, 0.8962],
         [0.3401, 0.0807]]])

### Zeros and ones


In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=0,end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating tensors like (same shape)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

### Tensor datatype is one of the 3 big errors you run into with pytorch and deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors:

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - get shape form a tensor, can use `tensor.shape`
3. Tensors not on the right device - get gevice from a tensor, can use `tensor.device`

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6335, 0.6863, 0.2964, 0.7420],
        [0.3233, 0.1433, 0.4788, 0.3558],
        [0.9145, 0.5960, 0.1852, 0.6567]])

In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* addtion
* subtraction
* Multiplication (element wise)
* division
* matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
# Mutltiply tensor by 10
tensor *= 10

In [ ]:
tensor - 10

tensor([ 0, 10, 20])

In [ ]:
# Try out pytroch bulit in funcs
# When you can, use the operators because they're more understandable.
torch.mul(tensor, 10)

tensor([100, 200, 300])

### Matrix multiplication

Two main ways of performing matrix mult in NN and Deep learning

1. Element Wise multiplication
2. Matrix multiplication (dot product)


In [ ]:
# Element wise mult

print (f"{tensor} * {tensor}")
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [ ]:
# Matrix mult by hand
1 * 1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 1.81 ms, sys: 0 ns, total: 1.81 ms
Wall time: 1.9 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 87 µs, sys: 0 ns, total: 87 µs
Wall time: 91.1 µs


tensor(1400)

### Rules that need to be satisfied with matrix multiplication
@ symbol is another symbol for matrix multiplication
1. Shape Errors (Inner dims must match)
`3x2 @ 2x3 - will work
3x2 @ 3x2 - won't work`
2. The resulting matrix has the shape of the *** outer dimensions***
`(2,3) @ (3,2) -> (2,2)`

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8999, 0.6617],
        [0.3029, 0.2970]])

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
#torch.mm(tensor_A, tensor_B) ## torch.mm is same as matmul

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.

In [ ]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# The matrix mult operation works when tensor_B is transposed
print(f"original shapes: tensor A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape} same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"multiplying: tensor_A @ tensor_B.T <- Inner dims must match")
print("output: ")
print(torch.mm(tensor_A, tensor_B.T))

original shapes: tensor A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]) same shape as above, tensor_B.T = torch.Size([2, 3])
multiplying: tensor_A @ tensor_B.T <- Inner dims must match
output: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Find the min, max, mean, sum, etc. (Tensor aggregtion)

In [ ]:
#create a tensor
x = torch.arange(1,100,10)
x.dtype

torch.int64

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#note, torch.mean requires a tensor of float32,
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dim
# The reshape has to be compatible with the original size.
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x ( because a view of a tensor shares the same memory as input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stack = torch.stack([x,x,x,x], dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
random_tensor = torch.rand(1,1,5,2,1)
random_tensor, random_tensor.shape

(tensor([[[[[0.7775],
            [0.0310]],
 
           [[0.8235],
            [0.4433]],
 
           [[0.7764],
            [0.9541]],
 
           [[0.9357],
            [0.3938]],
 
           [[0.0352],
            [0.8359]]]]]),
 torch.Size([1, 1, 5, 2, 1]))

In [ ]:
random_squeeze = torch.squeeze(random_tensor)
random_squeeze, random_squeeze.shape

(tensor([[0.7775, 0.0310],
         [0.8235, 0.4433],
         [0.7764, 0.9541],
         [0.9357, 0.3938],
         [0.0352, 0.8359]]),
 torch.Size([5, 2]))

In [ ]:
#Torch.unsqueeze - adds a single dim to a traget tensor at a specific dim.

print(f"previous target: {random_squeeze}")
print(f"Previous shape: {random_squeeze.shape}")

#Add an extra dim with unsqueeze
x_unsqueezed = random_squeeze.unsqueeze(dim=1)
print(f"new tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

previous target: tensor([[0.7775, 0.0310],
        [0.8235, 0.4433],
        [0.7764, 0.9541],
        [0.9357, 0.3938],
        [0.0352, 0.8359]])
Previous shape: torch.Size([5, 2])
new tensor: tensor([[[0.7775, 0.0310]],

        [[0.8235, 0.4433]],

        [[0.7764, 0.9541]],

        [[0.9357, 0.3938]],

        [[0.0352, 0.8359]]])
new shape: torch.Size([5, 1, 2])


In [ ]:
# Torch.permute = rearragnes the dims of a target tensor in a specfied order

x = torch.randn(size=(224,224, 3)) #[height, width, color channels]
x.size()
#Permute original tensor
torch.permute(x, (2,0,1)).size() #Color channels, height , width

torch.Size([3, 224, 224])

### Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#LEt's index on our middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Let's index on our most inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# you can use a ":" to select "All" of a target dimension
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:, 1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of 0 dim but only 1 index fo 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index of 0 of 0th and 1st dminesion and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
print(f"indexing to get 9: {x[:, 2, 2]}")
#index on x to return 3, 6, 9
print(f"indexing to get 3, 6, 9: {x[:, :, 2]}")

indexing to get 9: tensor([9])
indexing to get 3, 6, 9: tensor([[3, 6, 9]])


### Pytorch tensors and numpy

numpy is a popular scientific python numerical computing library
and because of this, pytorch has functionality to interact with it.

* Data in numpy, want in pytorch tensor -> torch.from_numpy
* Pytorch tensor -> Numpy -> torch.tensor.numpy()


In [ ]:
import torch
import numpy as np

arr = np.arange(1.0,8.0)
tensor = torch.from_numpy(arr) # Warning: when converting from numpy to pytorch, default type is float 64, not 32. change w/ .type()
arr,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
# Change the value of array, what will this do to tensor
arr = arr +1

arr, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy arr
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to numpy-tensor?

tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducibility (trying to take the random out of random)

In short how a nn works
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again ....`

To reduce randomness in Nn and pytorch comes the concept of a *** Random Seed ***
Essentially what the random seed does is 'flavour' the randomness

In [ ]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6493, 0.1885, 0.2287, 0.4294],
        [0.6505, 0.0499, 0.2685, 0.9798],
        [0.8418, 0.1911, 0.9277, 0.4705]])
tensor([[0.3063, 0.9785, 0.1406, 0.0816],
        [0.1686, 0.1333, 0.7936, 0.8672],
        [0.5808, 0.5402, 0.6179, 0.3442]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
# IT needs to be called every time you want it to be used.
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C== random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors in GPUs
GPUs = fast computation.

### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchaing a GPU
3. use cloud computing - GCP, AWS, Azure




For 2,3 Pytorch + GPU drivers (cuda) takes a little bit. Refer to pytorch documentation.



In [ ]:
!nvidia-smi

Sat Oct 28 15:34:22 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. check for GPU access with pytorch


In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [3]:
# Count number of devices
torch.cuda.device_count()

1

# putting tensors and models on the GPU
The reason we want our tensors / modesl on the GPU, is because GPu is fater computations


In [4]:
# Create a tesor (defualt is CPU)
tensor = torch.tensor([1,2,3], device="cpu")
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
# mvoe tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU


In [ ]:
#If tensor is on GPU, can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [7]:
#To fix the GPU tesnor with numpy issue, we can first set it to the CPU.
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [8]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Exercises

In [10]:
# 2
x = torch.rand(size=(7,7))
x

tensor([[0.8092, 0.5285, 0.6363, 0.8641, 0.2387, 0.2375, 0.6475],
        [0.8989, 0.0223, 0.9838, 0.5245, 0.0463, 0.7394, 0.8387],
        [0.0088, 0.0804, 0.6153, 0.1745, 0.0802, 0.2260, 0.7714],
        [0.5675, 0.9763, 0.7632, 0.6945, 0.5308, 0.8170, 0.7464],
        [0.1943, 0.4236, 0.9339, 0.9716, 0.1392, 0.0471, 0.0198],
        [0.6196, 0.1441, 0.7642, 0.1724, 0.3039, 0.6834, 0.8680],
        [0.0769, 0.9778, 0.4508, 0.9604, 0.2608, 0.6693, 0.1640]])

In [11]:
y = torch.rand(size=(7,2))
torch.mm(x,y)

tensor([[2.0457, 1.4726],
        [2.1744, 1.1060],
        [1.0052, 0.5644],
        [3.0544, 2.3305],
        [1.5879, 0.9827],
        [1.9875, 1.2516],
        [2.2657, 1.7036]])

In [17]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
x = torch.rand(7, 2)
torch.manual_seed(RANDOM_SEED)
y = torch.rand(7, 2)

print(f"x: {x}")
print(f"y: {y.T}")
print(f"x == y.T {x == y}")

torch.matmul(x,y.T)

x: tensor([[0.4963, 0.7682],
        [0.0885, 0.1320],
        [0.3074, 0.6341],
        [0.4901, 0.8964],
        [0.4556, 0.6323],
        [0.3489, 0.4017],
        [0.0223, 0.1689]])
y: tensor([[0.4963, 0.0885, 0.3074, 0.4901, 0.4556, 0.3489, 0.0223],
        [0.7682, 0.1320, 0.6341, 0.8964, 0.6323, 0.4017, 0.1689]])
x == y.T tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])


tensor([[0.8364, 0.1453, 0.6397, 0.9319, 0.7119, 0.4817, 0.1408],
        [0.1453, 0.0253, 0.1109, 0.1617, 0.1238, 0.0839, 0.0243],
        [0.6397, 0.1109, 0.4966, 0.7191, 0.5410, 0.3620, 0.1139],
        [0.9319, 0.1617, 0.7191, 1.0438, 0.7901, 0.5311, 0.1623],
        [0.7119, 0.1238, 0.5410, 0.7901, 0.6074, 0.4130, 0.1169],
        [0.4817, 0.0839, 0.3620, 0.5311, 0.4130, 0.2831, 0.0756],
        [0.1408, 0.0243, 0.1139, 0.1623, 0.1169, 0.0756, 0.0290]])

In [19]:
if torch.cuda.is_available :
  RANDOM_SEED = 1234
  torch.cuda.manual_seed(RANDOM_SEED)
  x = torch.tensor([1,2,3,4], device="cuda")


In [25]:
device = "cuda"
x = torch.rand(2,3)
y = torch.rand(2,3)
x.to(device)
y.to(device)
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)
z = torch.mm(x,y.T)

In [26]:
min = torch.min(z)
max = torch.max(z)
min, max

(tensor(0.8921), tensor(1.2261))

In [29]:
torch.manual_seed(7)
rand_tensor = torch.rand(1,1,1,10)
squeezed_rand = torch.squeeze(rand_tensor)
print(rand_tensor)
print(squeezed_rand)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
