<a href="https://colab.research.google.com/github/samuelj1323/By_The_Cover/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
If you have any questions: go to the course github


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


## Intro to Tensors

### Creating a tensor



In [2]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

Torch tensor: https://pytorch.org/docs/stable/tensors.html
.

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
#Typically has more than one number

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix

MATRIX = torch.tensor([[7,8],
[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random Tensors

Why random tensors?
Random tensors are important because the way taht many NN learn is that htey start with tensors ful of rnadom numbers and hten adjust those random numbers to better represent the data.

`Start with Random number -> look at data => update random numbers => look at data => update the random numbers `

In [16]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5222, 0.5928, 0.5048, 0.7952],
        [0.4604, 0.0834, 0.2227, 0.9893],
        [0.7517, 0.8583, 0.0729, 0.9757]])

In [17]:
random_tensor.ndim

2

In [18]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
torch.rand(2,3,2)

tensor([[[0.7620, 0.8413],
         [0.3633, 0.6285],
         [0.2774, 0.0065]],

        [[0.8273, 0.8595],
         [0.9036, 0.1528],
         [0.4405, 0.7372]]])

### Zeros and ones


In [20]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=0,end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Creating tensors like (same shape)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

### Tensor datatype is one of the 3 big errors you run into with pytorch and deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors:

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - get shape form a tensor, can use `tensor.shape`
3. Tensors not on the right device - get gevice from a tensor, can use `tensor.device`

In [31]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0602, 0.7241, 0.0635, 0.3305],
        [0.7515, 0.2259, 0.8478, 0.7664],
        [0.0046, 0.7115, 0.0640, 0.2063]])

In [32]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* addtion
* subtraction
* Multiplication (element wise)
* division
* matrix multiplication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [37]:
# Mutltiply tensor by 10
tensor *= 10

In [39]:
tensor - 10

tensor([ 0, 10, 20])

In [40]:
# Try out pytroch bulit in funcs
# When you can, use the operators because they're more understandable.
torch.mul(tensor, 10)

tensor([100, 200, 300])

### Matrix multiplication

Two main ways of performing matrix mult in NN and Deep learning

1. Element Wise multiplication
2. Matrix multiplication (dot product)


In [44]:
# Element wise mult

print (f"{tensor} * {tensor}")
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [46]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [47]:
# Matrix mult by hand
1 * 1 + 2*2 + 3*3

14

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 2.41 ms, sys: 92 µs, total: 2.5 ms
Wall time: 2.18 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.04 ms, sys: 10 µs, total: 1.05 ms
Wall time: 5.15 ms


tensor(1400)

### Rules that need to be satisfied with matrix multiplication
@ symbol is another symbol for matrix multiplication
1. Shape Errors (Inner dims must match)
`3x2 @ 2x3 - will work
3x2 @ 3x2 - won't work`
2. The resulting matrix has the shape of the *** outer dimensions***
`(2,3) @ (3,2) -> (2,2)`

In [52]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.6189, 1.6359],
        [0.3377, 0.6700]])

In [58]:
# Shape for matrix multiplication
"""tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A, tensor_B) ## torch.mm is same as matmul"""

'tensor_A = torch.tensor([[1,2],[3,4],[5,6]])\ntensor_B = torch.tensor([[7,10],[8,11],[9,12]])\ntorch.mm(tensor_A, tensor_B) ## torch.mm is same as matmul'

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.

In [54]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [55]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [57]:
# The matrix mult operation works when tensor_B is transposed
print(f"original shapes: tensor A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape} same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"multiplying: tensor_A @ tensor_B.T <- Inner dims must match")
print("output: ")
print(torch.mm(tensor_A, tensor_B.T))

original shapes: tensor A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]) same shape as above, tensor_B.T = torch.Size([2, 3])
multiplying: tensor_A @ tensor_B.T <- Inner dims must match
output: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Find the min, max, mean, sum, etc. (Tensor aggregtion)

In [73]:
#create a tensor
x = torch.arange(1,100,10)
x.dtype

torch.int64

In [74]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [75]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [76]:
#note, torch.mean requires a tensor of float32,
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [77]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [78]:
x.argmin()

tensor(0)

In [79]:
x.argmax()

tensor(9)

In [ ]:
# LEft off on video 25, start there.