In [1]:
import numpy as np
def cos_mat(train_mat):
    user_train_like = []
    for u in range(len(train_mat)):
        user_train_like.append(np.where(train_mat[u, :] > 0)[0])

    numer = np.matmul(train_mat, train_mat.T)
    denom = np.sum(train_mat ** 2, axis=1, keepdims=True) ** 0.5
    Cosine = numer / np.matmul(denom, denom.T)
    return Cosine

"""#Here is a way to create recommendations based on the cosine function (not needed )
recommendation = []
for u in range(num_user):
    similarities = Cosine[u, :]
    similarities[u] = -1
    N_idx = np.argpartition(similarities, -10)[-10:]
    N_sim = similarities[N_idx]
    scores = np.sum(N_sim.reshape((-1, 1)) * train_mat[N_idx, :], axis=0) / np.sum(N_sim)

    train_like = user_train_like[u]
    scores[train_like] = -9999
    top50_iid = np.argpartition(scores, -50)[-50:]
    top50_iid = top50_iid[np.argsort(scores[top50_iid])[-1::-1]]
    recommendation.append(top50_iid)
recommendation = np.array(recommendation)
"""
print("fin")

fin


In [2]:
def cos_array(array_2d): #takes in one 2d np array
    d = array_2d.T @ array_2d
    norm = (array_2d * array_2d).sum(0, keepdims=True) ** .5
    return d / norm / norm.T
    

In [5]:
m = np.array([
        [ 0.0072427 ,  0.00669255,  0.00785213,  0.00845336,  0.01042869],
        [ 0.00710799,  0.00668831,  0.00772334,  0.00777796,  0.01049965],
        [ 0.00741872,  0.00650899,  0.00772273,  0.00729002,  0.00919407],
        [ 0.00717589,  0.00627021,  0.0069514 ,  0.0079332 ,  0.01069545],
        [ 0.00617369,  0.00590539,  0.00738468,  0.00761699,  0.00886915]
    ])
print(cos_array(m))

[[1.         0.99935263 0.99787511 0.99728263 0.99774544]
 [0.99935263 1.         0.99930407 0.99852672 0.99812953]
 [0.99787511 0.99930407 1.         0.99804949 0.99578657]
 [0.99728263 0.99852672 0.99804949 1.         0.99847273]
 [0.99774544 0.99812953 0.99578657 0.99847273 1.        ]]


Sorry for the confusion, Hopfully this helps.